### ISSUE TITLE
Einige Handzeichen-Bilder fehlen

### ISSUE THREAD

**Issue by mgkurtz** [Die-KoMa/neulingsheft#1]
Manche Handzeichen-Bilder sind nicht so trivial aus https://die-koma.org/wiki-beta/Datei:Neulingsheft.pdf  zu exportieren. Das sollte allerdings noch geschehen. Alternativ könnte man auch neue Bilder designen.

**Comment by jplitza** [comment]
Warum nehmt ihr sie dann nicht aus dem original SVN?

**Comment by mgkurtz** [comment]
> Warum nehmt ihr sie dann nicht aus dem original SVN?

Auf das Original hatte leider niemand Zugriff auf der KoMa und bevor da nichts passiert, habe ich das Heft (als Plenumsbeschäftigungsmaßnahme) lieber neu geTeXt und hier hochgeladen. Fühl dich aber gerne frei, den alten Code oder die Bilder hier hochzuladen oder mir zukommen zu lassen.

**Comment by jplitza** [comment]
Mir ist die Lizenz des Originals nicht klar, deswegen pushe ich das nicht einfach hier hin. Die SVN-Historie legt nahe, dass @cordlandwehr das gemacht hat, mit seinem OK hätte ich da kein Problem mit.
Alternativ hat das KoMa-Büro aber Zugriff auf das "KoMa-Orga"-Projekt auf fachschaften.org, dort findet sich der Quellcode.

**Comment by cordlandwehr** [comment]
Hi, für mich wäre das total OK, das SVN hier öffentlich zu machen. Den Quellcode können wir bei der Gelegenheit auch gerne unter eine passende Lizenz stellen (CC-BY?) Bei den Bildern kann ich leider nicht mehr genau sagen, woher sie alle stammen (ein paar habe ich allerdings selbst gemalt). Manche Teile, wie das KoMa ABC, habe ich auch einfach aus dem Neulingsflyer von Gesa und anderen (ca. 2005/2006) in das Neulingsheft übernommen.

**Comment by nicoa** [comment]
@mgkurtz können wir den Issue wieder öffnen und vielleicht darüber diskutieren bei der nächsten Koma ob wir die alte Historie mit einarbeiten (und die Lizenz adaptieren bzw. anpassen bzw. erfragen was da gewünscht ist)? Wäre aus Histo-Gründen vielleicht ganz schön und das rein mergen kann ich gerne übernehmen ;-)
