### ISSUE TITLE
Aktualisierung der Handzeichen

### ISSUE THREAD

**Issue by mgkurtz** [Die-KoMa/neulingsheft#2]
Beschreibungen in https://github.com/Die-KoMa/neulingsheft/blob/master/handzeichen.tex überarbeiten, insbesondere Neuerungen der KoMa82 und KoMa83.

**Comment by StefanAugsburg** [comment]
Bilder für die neuen Handzeichen erstellen

**Comment by mgkurtz** [comment]
Geschlossen in 5792b06. Danke Tam!
